# ベースイメージの指定
#PCにイメージが取得済であればそれを使用する
#PCにイメージがない場合、DockerHubから取得する。
FROM python:3.9-slim

# metadata
LABEL maintainer="fwpc0811@gmail.com"
LABEL version="1.0"
LABEL description="simple python image."

# change working dir.
WORKDIR /tmp/mydir
